<?php

use App\Http\Middleware\SecurityHeaders;

if (!function_exists("csp_nonce")) {
    /**
     * Return the per-request CSP nonce generated by SecurityHeaders middleware.
     * Use in Blade templates as {{ csp_nonce() }} or via the @cspNonce directive.
     */
    function csp_nonce(): string
    {
        return request()->attributes->get(SecurityHeaders::NONCE_KEY, "");
    }
}
