@extends('layouts.app')
@section('page-title', 'Attendance QR')

@section('content')
<div class="tch-card" style="max-width:700px;margin:auto;">
    <div class="tch-card-head"><div class="tch-card-title"><i class="bi bi-qr-code me-2"></i> Student Assistant</div></div>
    <div style="padding:24px;">
        <h1 style="font-size:1.4rem;color:#f3e7cd;">{{ $session->subject?->name }}</h1>
        <p style="color:#b39b82;">{{ $session->subject?->section }} · Session ends {{ $session->session_ends_at->format('h:i A') }}</p>
        <div id="assistantQrMessage" role="status" aria-live="polite" style="color:#b39b82;margin-bottom:16px;">Connecting to attendance session...</div>
        <div id="assistantQrCanvas" aria-label="Current attendance QR code" style="display:none;width:max-content;max-width:100%;background:#fff;padding:14px;border-radius:14px;margin:0 auto 16px;"></div>
        <div class="d-flex justify-content-between flex-wrap gap-2" style="color:#b39b82;">
            <span>QR Status: <strong id="assistantQrStatus" style="color:#f3e7cd;">Checking</strong></span>
            <span>Refreshes in: <strong id="assistantQrCountdown" style="color:#f3e7cd;">--:--</strong></span>
        </div>
        <p style="color:#b39b82;margin-top:12px;">Generated by: <span id="assistantQrGenerator">—</span></p>
        <button id="assistantQrReplace" type="button" class="tch-btn tch-btn-primary">Generate New QR</button>
    </div>
</div>
@endsection

@push('scripts')
<script src="{{ asset('js/qrcode.min.js') }}"></script>
<script>
(() => {
    const baseUrl = @json(route('student-assistant.qr.status', $session));
    const generateUrl = @json(route('student-assistant.qr.generate', $session));
    const rotateUrl = @json(route('student-assistant.qr.rotate', $session));
    const replaceUrl = @json(route('student-assistant.qr.replace', $session));
    let sessionEndsAt = {{ $session->session_ends_at->timestamp * 1000 }};
    const csrf = document.querySelector('meta[name="csrf-token"]').content;
    const canvas = document.getElementById('assistantQrCanvas');
    const message = document.getElementById('assistantQrMessage');
    const status = document.getElementById('assistantQrStatus');
    const countdown = document.getElementById('assistantQrCountdown');
    const generator = document.getElementById('assistantQrGenerator');
    const replaceButton = document.getElementById('assistantQrReplace');
    let currentId = null;
    let expiresAt = 0;
    let busy = false;
    let retryDelay = 1000;

    function clearQr(text) {
        canvas.replaceChildren();
        canvas.style.display = 'none';
        currentId = null;
        expiresAt = 0;
        status.textContent = text;
        countdown.textContent = '--:--';
    }

    function showQr(data) {
        if (data.session_ends_at) sessionEndsAt = data.session_ends_at * 1000;
        if (data.token_id !== currentId) {
            canvas.replaceChildren();
            new QRCode(canvas, {
                text: data.scan_url,
                width: Math.min(300, Math.floor(window.innerWidth * .7)),
                height: Math.min(300, Math.floor(window.innerWidth * .7)),
                colorDark: '#000000', colorLight: '#ffffff',
                correctLevel: QRCode.CorrectLevel.M
            });
            currentId = data.token_id;
        }
        canvas.style.display = 'block';
        expiresAt = data.expires_at * 1000;
        status.textContent = 'Active';
        generator.textContent = data.generated_by || 'Student Assistant';
        message.textContent = 'Students can scan this QR with their own devices.';
        tick();
    }

    function tick() {
        if (!expiresAt) return;
        const seconds = Math.max(0, Math.ceil((expiresAt - Date.now()) / 1000));
        countdown.textContent = String(Math.floor(seconds / 60)).padStart(2, '0') + ':' + String(seconds % 60).padStart(2, '0');
        if (seconds === 0 && !busy && navigator.onLine) {
            clearQr('Expired');
            requestQr(rotateUrl);
        }
    }

    function endSession() {
        clearQr('Ended');
        message.textContent = 'Attendance session has ended.';
        replaceButton.hidden = true;
    }

    async function requestQr(url) {
        if (busy) return;
        busy = true;
        replaceButton.disabled = true;
        status.textContent = 'Updating';
        try {
            const response = await fetch(url, {
                method: 'POST', credentials: 'same-origin',
                headers: { 'X-CSRF-TOKEN': csrf, 'Accept': 'application/json' }
            });
            const data = await response.json();
            if (response.status === 410) {
                endSession();
                return;
            }
            if (response.status === 403) {
                let ended = Date.now() >= sessionEndsAt;
                if (!ended) {
                    try {
                        ended = (await fetch(baseUrl, { credentials: 'same-origin' })).status === 410;
                    } catch (_) { /* Keep the original authorization failure. */ }
                }
                if (ended) endSession();
                else {
                    clearQr('Unauthorized');
                    message.textContent = 'You are no longer authorized to operate attendance for this class.';
                }
                replaceButton.hidden = true;
                return;
            }
            if (!response.ok || !data.success) {
                if (response.status === 422 && data.errors?.session) clearQr('Ended');
                message.textContent = data.message || Object.values(data.errors || {})[0]?.[0] || 'Unable to generate QR. Please try again.';
                return;
            }
            retryDelay = 1000;
            showQr(data);
        } catch (error) {
            message.textContent = 'Connection lost. Reconnect to the server before generating a new QR.';
            status.textContent = 'Disconnected';
            setTimeout(sync, retryDelay);
            retryDelay = Math.min(retryDelay * 2, 8000);
        } finally {
            busy = false;
            replaceButton.disabled = false;
        }
    }

    async function sync() {
        if (busy || !navigator.onLine) return;
        try {
            const response = await fetch(baseUrl, { credentials: 'same-origin', headers: { 'Accept': 'application/json' } });
            if (response.status === 410) {
                endSession();
                return;
            }
            if (response.status === 403) {
                clearQr('Unauthorized');
                message.textContent = 'You are no longer authorized to operate attendance for this class.';
                replaceButton.hidden = true;
                return;
            }
            if (!response.ok) throw new Error('Status unavailable');
            const data = await response.json();
            if (data.active) showQr(data);
            else if (!busy) requestQr(generateUrl);
        } catch (error) {
            message.textContent = 'Connection lost. Reconnect to the server before generating a new QR.';
            setTimeout(sync, retryDelay);
            retryDelay = Math.min(retryDelay * 2, 8000);
        }
    }

    replaceButton.addEventListener('click', () => requestQr(replaceUrl));
    const echo = window.Echo;
    if (echo) {
        echo.private('assistant-session.{{ $session->id }}')
            .listen('.attendance.qr.changed', () => sync())
            .listen('.attendance.session.changed', (event) => {
                if (event.change_type === 'closed') endSession();
                if (event.change_type === 'extended') sessionEndsAt = event.session_ends_at * 1000;
            });
        const connection = echo.connector?.pusher?.connection;
        connection?.bind('connected', () => { retryDelay = 1000; sync(); });
        connection?.bind('disconnected', () => {
            status.textContent = 'Disconnected';
            message.textContent = 'Connection lost. Reconnecting and checking current QR...';
            setTimeout(sync, retryDelay);
            retryDelay = Math.min(retryDelay * 2, 8000);
        });
    }
    window.addEventListener('online', sync);
    window.addEventListener('offline', () => { status.textContent = 'Disconnected'; message.textContent = 'Connection lost. Reconnect to the server before generating a new QR.'; });
    setInterval(tick, 1000);
    setInterval(sync, 5000);
    sync();
})();
</script>
@endpush
